# Generated by Django 4.2 on 2023-04-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_slug_to_product'),
    ]

    operations = [
        # first is for upgrading and second is for downgrading db 
        migrations.RunSQL("""
        INSERT INTO store_collection (title) 
        VALUES ('collection1')
        """ , """
        DELETE FROM store_collection WHERE title = 'collection1'
        """)

    ]
 